### ISSUE TITLE
Review current classes and functions and come up with suggestions for improvement

### ISSUE THREAD

**Issue by TCACastelijns** [MLblog/jads_kaggle#14]

**Comment by TCACastelijns** [comment]
I just tested the notebooks on my machine. I have a couple of questions/remarks. 

- With PyCharm I have issues to run the notebooks. This is because I added a project, taking all files of jads_kaggle into account. For some reason, PyCharm is assuming the main folder as working directory. The relative paths in the notebooks are not working under these conditions. However, running the scripts in Jypyter will work anyway. Dyou have suggestions to solve this? Without having a project for every single script.

- Notebooks are saved multiple times during the experiments. Even without remarkable changes, your notebooks will change. I think it is important that everyone should checkout the files if he/she is done with the experiments. Your notebooks will go back to the initial versions. In that case you do not have to commit/push the files and you keep the original versions from the base as local versions. If you agree, I will put this in the CONTRIBUTING.md file / or add a specific README.md file in the notebook folder.

**Comment by steremma** [comment]
Good point Thomas. Here is what I think:

1. DIfferent IDEs have different configuration of what they consider the `root directory`. As a result
running scripts from them is rarely a good option. For this reason I propose that we get rid of all the mains and instead create notebooks to show how are function/classes are used (like my last push on `tuning` for example).

2. This is indeed an important observation that I briefly discussed with @san89 but it should also be part of the contribution guide. Indeed changes in output should not be tracked. Everytime someone wants to push changes to a notebook please make sure to delete all output. Changes made at the experimentation phase should be discarded by `git checkout filename.ipynb`. It would be great if you can make that clear in the guide!

**Comment by steremma** [comment]
Actually a `toxicity/notebooks` specific `README.md` is a better place for this last point, I just noticed your last sentence!
