### ISSUE TITLE
Sentiment analysis as an additional feature

### ISSUE THREAD

**Issue by san89** [MLblog/jads_kaggle#16]
Sentiment analysis may be done including external data sets.

**Comment by steremma** [comment]
Many external datasets can be found [here](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/discussion/46035)

**Comment by steremma** [comment]
@san89 Since your most recent PR addresses this issue, should we close it? Or do you plan to add more dictionaries/APIs related to precalculated sentiment scores in the future?

**Comment by san89** [comment]
@steremma I would like to Include the Google sentiment analysis as an additional feature:

https://cloud.google.com/natural-language/docs/sentiment-tutorial

**Comment by steremma** [comment]
Ok keeping this open then 👍

**Comment by san89** [comment]
If we want to proceed with the Google API we must provide personal information such as credit card account, which is an inconvenient situation. Instead, I found this interesting repository of a team that won a sentiment analysis competition at Kaggle:

https://github.com/Wronskia/Sentiment-Analysis-on-Twitter-data/tree/master/Final

I will rater go for this approach.

**Comment by san89** [comment]
@steremma Could you please close this issue. It was already solved :)
