### ISSUE TITLE
Implement parallel processing for Bayesian Optimization

### ISSUE THREAD

**Issue by joepvdbogaert** [MLblog/jads_kaggle#37]
Currently, the advantages of using Bayesian Optimization to tune a model are limited, since it only uses one core. To fully harvest the benefits of BO, we need to use more. I think it is implemented in the used package (GPyOpt), so we just need to integrate it in our function.

**Comment by steremma** [comment]
Should I wait for the change in #36 or are we going to make a new PR for the parallelization later?

**Comment by joepvdbogaert** [comment]
I think I can fix that today. Is is possible to add that to this PR somehow?

**Comment by steremma** [comment]
if you just to your branch in your fork, the PR will be automatically updated, you don't need to change anything :)

**Comment by joepvdbogaert** [comment]
Cool, on it!
