### ISSUE TITLE
IndexError in dimensionality reduction

### ISSUE THREAD

**Issue by joepvdbogaert** [MLblog/jads_kaggle#46]
I tried running the dimensionality reduction notebook with the LSI setting, but ran in the following error.

<pre>
Tokenizing text, this will take a while...
Creating the gensim corpora, this will take a while...
Using gensim's implementation of TF-IDF, this will take a while...
Creating the LSI model, this will take a while...
Reformatting output to a 2D array, this will take a while...
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-860b66107de6> in <module>()
----> 1 train_x, test_x = gensim_preprocess(train, test, model_type='lsi', num_topics=500, report_progress=True, data_dir=DATA_ROOT)

~\Documents\JADS Working Files\JADS Kaggle\jads_kaggle\toxicity\preprocessing.py in wrap(*args, **kwargs)
     20     """
     21     def wrap(*args, **kwargs):
---> 22         train, test = f(*args, **kwargs)
     23         assert(train.shape[1] == test.shape[1])
     24         return train, test

~\Documents\JADS Working Files\JADS Kaggle\jads_kaggle\toxicity\utils.py in wrap(*args, **kwargs)
     16     def wrap(*args, **kwargs):
     17         start = time.time()
---> 18         ret = f(*args, **kwargs)
     19         stop = time.time()
     20         print('{} function took {:.1f} seconds to complete\n'.format(f.__name__, (stop - start)))

~\Documents\JADS Working Files\JADS Kaggle\jads_kaggle\toxicity\preprocessing.py in gensim_preprocess(train, test, model_type, num_topics, use_own_tfidf, force_compute, report_progress, data_dir, **tfidf_params)
    168     print("Reformatting output to a 2D array, this will take a while...")
    169     values = np.vectorize(lambda x: x[1])
--> 170     return values(np.array(train)), values(np.array(test))
    171 
    172 

~\Anaconda3\lib\site-packages\numpy\lib\function_base.py in __call__(self, *args, **kwargs)
   2753             vargs.extend([kwargs[_n] for _n in names])
   2754 
-> 2755         return self._vectorize_call(func=func, args=vargs)
   2756 
   2757     def _get_ufunc_and_otypes(self, func, args):

~\Anaconda3\lib\site-packages\numpy\lib\function_base.py in _vectorize_call(self, func, args)
   2829                       for a in args]
   2830 
-> 2831             outputs = ufunc(*inputs)
   2832 
   2833             if ufunc.nout == 1:

~\Documents\JADS Working Files\JADS Kaggle\jads_kaggle\toxicity\preprocessing.py in <lambda>(x)
    167     # Transform into a 2D array format.
    168     print("Reformatting output to a 2D array, this will take a while...")
--> 169     values = np.vectorize(lambda x: x[1])
    170     return values(np.array(train)), values(np.array(test))
    171 

IndexError: list index out of range
</pre>

**Comment by steremma** [comment]
Oh I think I remember: There is a single corrupted row in `test` which causes this, I manually deleted it from the CSV and forgot to add it in the code. You can try to:

a) Replace `lambda x: x[1]` with a named function like:
```
def safe_get(x):
  try:
    return x[1]
  except IndexError:
    return None
```
b) Manually delete the bad line from the CSV (quick & dirty)

**Comment by steremma** [comment]
**UPDATE**
I tried to fix the issue and apparently it harder than I thought. the `lsi` module has a lot of trouble handling small documents, and many documents in our corpus contain less than 10 words. 

We could exclude them but we are giving up too much information. Since I have very limited time, I propose we stick on the wider representations for now unless someone else can solve the bug.

**Comment by steremma** [comment]
Probably yes! The sklearn one might work out of the box

**Comment by joepvdbogaert** [comment]
Alright, will take a look at it tonight.

**Comment by joepvdbogaert** [comment]
<strong>UPDATE</strong>
It appears that the TF-IDF implementations were the problem. I now switched to sklearn's implementation of both TF-IDF and dimensionality reduction (TruncatedSVD, which is the same as LSA / LSI in this context) and it seems to work. It still uses the NLTK tokenizer. PR coming up, running one more test now.
