### ISSUE TITLE
Current virtual environment is uncompatible with Keras and Tensorflow

### ISSUE THREAD

**Issue by joepvdbogaert** [MLblog/jads_kaggle#51]
Installing Keras or Tensorflow in the kaggle_env on Windows results in conflicts with other packages and possibly messes up your entire conda installation. Both @san89 and me had to reinstall anaconda completely on our machines.

My workaround now is to just not use the kaggle_env when using those packages, but a more sustainable solution would be nice. Perhaps removing unused packages from the environment could help or we need to find if there are specific issues with those packages when installing them in a virtual environment.

**Comment by steremma** [comment]
This is a two-fold problem:
* Tensorflow is problematic on windows in general.
* Conda indeed includes many useless packages.

I propose that we switch over to `pip` starting with our next competition, it is much cleaner in general. The only reason why we went with `conda` to begin with is that `virtualenv` has some issues in Windows but we can make it work with the `virtualenvwrapper` and update the `Contributing.md` accordingly to help others.

**Comment by joepvdbogaert** [comment]
Thanks to @san89 we have a new approach now. I'm closing this.
