### ISSUE TITLE
Preprocessing adds unique IDs to data

### ISSUE THREAD

**Issue by joepvdbogaert** [MLblog/jads_kaggle#94]
Somewhere in our preprocessing steps, the fullVisitorId gets screwed up. From the load notebook:

```
train = load("../data/train.csv", nrows=10000)
test = load("../data/test.csv", nrows=None)
print(test["fullVisitorId"].nunique())
```
Loaded file ../data/train.csv
Shape is: (10000, 54)
Loaded file ../data/test.csv
Shape is: (804684, 53)
617242

_NOTE: so far it is correct, the expected number of IDs is 617242. But after the next step:_

```
train_processed, test_processed = process(train, test)
print(test_processed["fullVisitorId"].nunique())
```
Dropping constant columns...
Generating date columns...
Finding total visits...
Splitting back...
618207

There is suddenly a thousand more. Clearly, this way we cannot produce the required predictions. This happened before when we didn't read the `fullVisitorId` column as a string. Now we do, but somewhere in `process()` it seems to go wrong. The number of observations in the datasets does not change, so I guess it is a data type thing. Is it implicitly converted to numeric somewhere?

**Comment by joepvdbogaert** [comment]
Got a fix, PR coming up.

**Comment by steremma** [comment]
Out of curiosity, can you point out where the error happened in the PR or here?

**Comment by joepvdbogaert** [comment]
I'm not entirely sure where, but somewhere when working on the merged/concatenated data, the data is sorted. Probably some internal Pandas thing?

**Comment by steremma** [comment]
This behavior changed between pandas version but I though the `sort` argument: `merged = pd.concat([train, test], sort=False)`  would take care of this. Apparently it doesn't

**Comment by steremma** [comment]
Oh but I see, the problem happens after the `merge`. So it could be anything. Your fix seems fine to be though let's merge asap.

**Comment by joepvdbogaert** [comment]
Yeah exactly, in one of the preprocessing steps after merging and before splitting, but it's hard to say where. So this was the quickest solution I guess.
